services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb

    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.couchdb.rule=Host(`couch.nenad.cloud`)"
      - "traefik.http.routers.couchdb.entrypoints=websecure"
      - "traefik.http.routers.couchdb.tls.certresolver=le"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"
      - "traefik.docker.network=proxy"

    volumes:
      - ./couchdb-data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/cors.ini

    networks:
      - apps_net
      - proxy

volumes:
  couchdb-data:


networks:
  apps_net:
  proxy:
    external: true
